### ISSUE TITLE
Multiple choice/quiz section

### ISSUE THREAD

**Issue by jshor** [paceuniversity/gsd2014-team3#16]
As a user, I want to have a multiple choice section with answers in Swahili and a question in English.

**Comment by scharffc** [comment]
Product backlog US stories have to be labelled as 'Product Backlog' 

Please also add the link that permits to access all the product backlog US to the wiki. 

@jshor

**Comment by jshor** [comment]
https://docs.google.com/spreadsheet/ccc?key=0AirLKgHXY96KdDRBZ2NNWUtjMUlnTW5WQjY2aGpmdHc&usp=drive_web#gid=1

**Comment by csakai** [comment]
I am closing this user story because there is a better explanation in #24
