### ISSUE TITLE
Conversation category choosing

### ISSUE THREAD

**Issue by jshor** [paceuniversity/gsd2014-team3#4]
As a user, I want to be able to choose from conversation categories such as greetings, counting and family, so that I can learn fundamentals of the language. I choose the category before beginning conversation with my conversation partner.

**Comment by csakai** [comment]
I have changed this user story to better convey how it will be implemented.

**Comment by jshor** [comment]
ambiguous duplicate of: https://github.com/paceuniversity/gsd2014-team3/issues/30
