### ISSUE TITLE
Bug: The displayed app name is not correct

### ISSUE THREAD

**Issue by yusa55** [paceuniversity/gsd2014-team3#45]
Environment:  Android OS
Reporter: Yussuf
Steps to Reproduce the bug:
•  Install the copy of jifunzeKiswahili.apk
Expected result: The name of the app should be Jifunze Kiswahili

Actual result: The name of the app shown as HelloWorld

Priority: high

Severity: high

Screen Short:
![bug 1](https://cloud.githubusercontent.com/assets/6734865/2886494/17fc6652-d4e7-11e3-9fe8-748664046cfb.jpg)

**Comment by jshor** [comment]
the app name has been corrected
