### ISSUE TITLE
Bug Report: When the app start it give only last option “Check your Dictionary” unless you rotate the device

### ISSUE THREAD

**Issue by yusa55** [paceuniversity/gsd2014-team3#46]
Environment: Android OS
Reporter: Yussuf
Steps to Reproduce the bug:
•  Launch the app by clicking the app button from the apps list
Expected result: The home layout should display all three kept linkable text.

Actual result: only one linkable text is displayed

Priority: high

Severity: high

Screen Short:
![bug 2](https://cloud.githubusercontent.com/assets/6734865/2886559/807212a8-d4e8-11e3-8916-728aa6c1e913.jpg)

**Comment by jshor** [comment]
the main menu is implemented in place of this
