### ISSUE TITLE
Bug report: When you click the “Take sample Quiz” sentence it open activity  with un relevant layout.

### ISSUE THREAD

**Issue by yusa55** [paceuniversity/gsd2014-team3#48]
Environment:
Reporter: Yussuf
Steps to Reproduce the bug:
•  Rotate the screen after launching the app to get all linkable text
Expected result: The user should be able to choose a quiz or automatically to start the quiz

Actual result: Blank page with red background and “translation” title at the top of red background”

Priority: high

Severity: high

Screen Short:
![bug 4](https://cloud.githubusercontent.com/assets/6734865/2886659/1e47b332-d4eb-11e3-9515-e7090182f7b4.jpg)

**Comment by csakai** [comment]
This link was a testing link since we had not set up the category chooser. In the final release, it will not be present. closing this.
