### ISSUE TITLE
Bug Report: At dictionary, no result displayed for the inserted word.

### ISSUE THREAD

**Issue by yusa55** [paceuniversity/gsd2014-team3#50]
Environment: Android OS
Reporter: Yussuf
Steps to Reproduce the bug:
•  Click on the dictionary clickable text from the home scree of the app
• Click on the textbox to launch a keyboard
• Type any word
• Click go from the keyboard
Expected result: the meaning of the inserted word or any message.

Actual result: nothing display

Priority: high

Severity: high

Screen Short:
![bug 6](https://cloud.githubusercontent.com/assets/6734865/2886738/be978900-d4ed-11e3-9578-af101c322835.jpg)

**Comment by csakai** [comment]
This has been resolved.
