### ISSUE TITLE
Bug Report: The option button at the top right corner gives options, in which neither is responding to any action when clicked rather than hide the popup menu.

### ISSUE THREAD

**Issue by mrutu** [paceuniversity/gsd2014-team3#52]
Environment: Android OS
Reporter: Daudi
Steps to Reproduce the bug:
•  Open choose category
• Click the top right button from the title bar
• Click any option from the popup menu
Expected result:  Relevant respond to the selected option

Actual result: all option to the same staff, closing the opened menu

Priority: high

Severity: high

Screen Short:
![bug 8](https://cloud.githubusercontent.com/assets/6747501/2886872/82037e74-d4f0-11e3-9f21-587a43ea84d8.jpg)

**Comment by csakai** [comment]
This has been resolved. That was an artifact of the code that was copied over from dictionary. That button will now take you to the dictionary chooser.
