### ISSUE TITLE
Bug Report: At “choose a category section” no option is clickable, so it doesn’t send a user to any place in the app.

### ISSUE THREAD

**Issue by mrutu** [paceuniversity/gsd2014-team3#53]
Environment: Android OS
Reporter: Daudi
Steps to Reproduce the bug:
•  Open choose category section by clicking its link from the home page of the app
• Try to click any item from the list

Expected result: To open new page according to the clicked category

Actual result: Nothing happen

Priority: high

Severity: high

Screen Short:
![bug 9](https://cloud.githubusercontent.com/assets/6747501/2886885/1f59a586-d4f1-11e3-9ca5-f27b3991acde.jpg)

**Comment by jshor** [comment]
fixed
