### ISSUE TITLE
Bug Report: When return back to the home page of the app from clicking the home button at the left upper corner, nothing is responding until you rotate the device.

### ISSUE THREAD

**Issue by mrutu** [paceuniversity/gsd2014-team3#54]
Environment: Android OS
Reporter: Daudi
• When the app is launched, click any linkable text from the given choice.
• Press the home button at the left corner of the title bar
• Before you rotate the device, try to click the available option
Expected result: all options should be available and click-able when return to home page of the app.

Actual result: only the last option is seen and not click-able as it should be

Priority: high

Severity: high

Screen Short:
![bug 10](https://cloud.githubusercontent.com/assets/6747501/2886904/a4b91fe0-d4f1-11e3-8e14-cd21304658a2.jpg)

**Comment by jshor** [comment]
The app now has a menu and is fixed to portrait mode.
