### ISSUE TITLE
Bug Report: Repetition of the contents in the choose category page, when returning from that page via home button and rotate the device and click again the choose category clickable text.

### ISSUE THREAD

**Issue by mrutu** [paceuniversity/gsd2014-team3#55]
Environment: Android OS
Reporter: Daudi
Steps to Reproduce the bug:
•  Open the app
• Choose the “choose category option
• Click the available home button at the left corner of the title bar.
• Rotate the scree to have all option
• Click again the “choose category option
Expected result: No repetition of the list item

Actual result: the items are repeated 

Priority: high

Severity: high

Screen Short:
![bug 11](https://cloud.githubusercontent.com/assets/6747501/2886941/76cce656-d4f2-11e3-979e-c89bc0258e5b.jpg)

**Comment by jshor** [comment]
fixed
